### PR TITLE
Further updates to README.md

### PR DESCRIPTION
**Pull request by twcau**
Have gone over it some more when I've had time this evening, and given it a serious spruce-up that I hope you'll appreciate.

**Summary of changes:**
- added a TOC;
- converted to proper H1-H3;
- cleaned up the layout and header order;
- added links (where appropriate) to jump back to an earlier part of the readme file for ease of navigation;
- used tables for some of the information for readability;
- made it easier to follow for DSM or SRM users;
- better spelt out what was needs to go where in the DDNS screen (good for those using assistive devices and aren't able to read the text in a screen shot);
- added in more references to Cloudflare help articles and pages on Cloudflare dash to find information;
- rooted out some spelling/grammar mistakes; and
- started singing the 12 Days of Christmas when writing this pull request comment just for my own laughs.

Hope you enjoy the suggestions and assistance. Thought since I'm not buying you a beer, this was the best way I could contribute back for the hours I've spent looking for a working solution to this.

### CODE REVIEW

**Comment by twcau** [comment]
Could have added some SRM-specific screen shots, but there really isn't much difference between what is shown in DSM, plus the screens are easy to follow anyway.

**Comment by mrikirill** [comment]
Thank you @twcau ! README.md looks great 👍🏼

**Comment by twcau** [comment]
Thanks, glad you appreciate it.
And seems the Synology crowd over at Reddit are appreciating your work too ;)
[Fantastic installable script for using Dynamic DNS with Cloudflare](https://www.reddit.com/r/synology/comments/hhrmc1/fantastic_installable_script_for_using_dynamic)

**Comment by mrikirill** [comment]
Oh wow 😀 So happy to see that it helps to someone else, not only cover my own cases

**Pull request merged**
